{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testchart.serviceAccountName" . }}
  annotations:
      argocd.argoproj.io/deletion-approved: "2025-12-19T13:07:02Z" 
      argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    {{- include "testchart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
